const places = [
	{
		id: "1",
		title: "Little Sturgeon Boat Launch",
		address: "3570 Co Rd CC, Sturgeon Bay, WI 54235, United States",
		content: "3570 Co Rd CC, Sturgeon Bay, WI 54235, United States",
		location: {
			icon: null,
			lat: "44.83772159999999",
			lng: "-87.56820270000003",
			city: "Gardner",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54235",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "2",
		title: "Olde Stone Quarry County Park",
		address: "4879 Bay Shore Drive, Sturgeon Bay, WI, United States",
		content: "4879 Bay Shore Drive, Sturgeon Bay, WI, United States",
		location: {
			icon: null,
			lat: "44.904134",
			lng: "-87.40502200000003",
			city: "Sevastopol",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54235",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "3",
		title: "Sawyer Park Boat Launch",
		address: "36 S Neenah Ave, Sturgeon Bay, WI, United States",
		content: "36 S Neenah Ave, Sturgeon Bay, WI, United States",
		location: {
			icon: null,
			lat: "44.8282049",
			lng: "-87.38099690000001",
			city: "Sturgeon Bay",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54235",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "4",
		title: "Egg Harbor Marina",
		address: "7815 Dock Rd, Egg Harbor, WI, United States",
		content: "7815 Dock Rd, Egg Harbor, WI, United States",
		location: {
			icon: null,
			lat: "45.0503443",
			lng: "-87.28222040000003",
			city: "Egg Harbor",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54209",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "5",
		title: "Sister Bay Marina",
		address: "10733 North Bay Shore Drive, Sister Bay, WI, United States",
		content: "10733 North Bay Shore Drive, Sister Bay, WI, United States",
		location: {
			icon: null,
			lat: "45.1923661",
			lng: "-87.11929510000004",
			city: "Sister Bay",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54234",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "6",
		title: "Rowleys Bay Resort Launch",
		address: "1041 Co Rd Zz, Sister Bay, WI, United States",
		content: "1041 Co Rd Zz, Sister Bay, WI, United States",
		location: {
			icon: null,
			lat: "45.218595",
			lng: "-87.03569700000003",
			city: "Liberty Grove",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54234",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "7",
		title: "Chaudoir's Dock County Park",
		address: "10863 County Rd N, Brussels, WI, United States",
		content: "10863 County Rd N, Brussels, WI, United States",
		location: {
			icon: null,
			lat: "44.7455797",
			lng: "-87.69794539999998",
			city: "Union",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54204",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "8",
		title: "Potawatomi State Park",
		address: "4200 Shoreline Rd, Sturgeon Bay, WI, United States",
		content: "4200 Shoreline Rd, Sturgeon Bay, WI, United States",
		location: {
			icon: null,
			lat: "44.880939",
			lng: "-87.42808500000001",
			city: "Nasewaupee",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54235",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "9",
		title: "Peninsula State Park",
		address: "Sunset Trail, Fish Creek, WI, United States",
		content: "Sunset Trail, Fish Creek, WI, United States",
		location: {
			icon: null,
			lat: "45.16913975565004",
			lng: "-87.22330215122071",
			city: "Gibraltar",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54212",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	},
	{
		id: "10",
		title: "Liberty Grove Public Boat Launch",
		address: "12030 Cedar Rd, Ellison Bay, WI 54210, United States",
		content: "12030 Cedar Rd, Ellison Bay, WI 54210, United States",
		location: {
			icon: null,
			lat: "45.2552037",
			lng: "-87.0736556",
			city: "Liberty Grove",
			state: "Wisconsin",
			country: "United States",
			redirect_url: "marker",
			redirect_custom_link: "",
			open_new_tab: "yes",
			postal_code: "54210",
			draggable: false,
			infowindow_default_open: "",
			animation: "DROP",
			infowindow_disable: false,
			zoom: 5
		},
		categories: [{ id: null, name: null, type: "category", icon: null }]
	}
];
